### ISSUE TITLE
Switch off Egypt "Heavy rain"

### ISSUE THREAD

**Issue by arsforza** [rodekruis/IBF-system#1556]
```[tasklist]
### Tasks
- [x] remove Egypt related data from production
- [x] remove Egypt related data from mock
- [x] check exceptions in code for Egypt and remove
- [x] remove users
- [x] remove mailchimp data (users / tags / segments)
- [ ] remove pipeline (check if Egypt and Uganda are separate)
- [ ] communicate to stakeholders
- [x] remove Egypt entries from indicator / layer metadata
- [x] remove relevant geoserver layers
- [x] remove pdf manual
```
