### ISSUE TITLE
[SPIKE] Create a priority matrix of components to test

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1583]
### **Who requested this spike**
@gulfaraz 

### **Functional or Technical Spike**
Devs will discuss and identify which components need to be tested.
Ideally, all components will have at least 3 tests each. This spike will decide which components get the first tests. Let's limit to 5 components in the frontend and 5 in the backend.

### **User Story**
As a tester
I want to know what to test
So that I can write the right tests

### **Acceptance Criteria**
- [ ] A document which lists the 10 components and what to test in those components
- [ ] Make this document accessible for reference in the upcoming months

### **Timebox**
At most an hour for the frontend and an hour for the backend.

```[tasklist]
### Tasks
- [x] Meeting on defining test cases e2e
- [ ] https://github.com/rodekruis/IBF-system/issues/1592
- [x] Follow-up meeting on API-tests/unit-tests
- [ ] Add E2E tests for subset of 'navigate dashboard' test cases (no-trigger)
- [ ] Create follow-up items
```

**Comment by diderikvw** [comment]
Refinement:
1. Have a meeting: Gulfaraz, Jannis, Piotr, Andrea.

**Comment by jannisvisser** [comment]
Meeting notes
- test cases (in order of priority)
  - login
  - loading dashboard after login with all of its components (map/timeline/chat/aggregate/header/action-summary/...)
    - start out with all elements in one test, but as we go we can decide to split up (estimate 1 day for all elements no-trigger)
  - navigating/interacting with the dashboard (select event, etc)
    - buttons in chat-component work as they should
    - map
      - layer overview should expand and close
      - layers toggleable
      - info popups on layer
      - hover over admin-areas
      - opening glofas station popup
      - collapsing legend
      - click on area? (ignore in no-trigger first)
    - check that timeline buttons are disabled
    - info icons in middle columns
    - change password (no prio) 
    - log out (no prio)
  - posting data (like saving early actions)
- start out with 1 disaster-type 1 country (Uganda floods)
- important dimension to split test case by: trigger / no -trigger (to expand later)
  - start with no-trigger
- expand from here to all disaster-types (1 country for each) as there are in practice many regression effects between disaster-types
- later expand to all countries (no prio) 
- notes on testing
  - test will show which step/element failed
- followup
  - Piotr will get started on above and we will get back later to priotiziatoin and what exactly is in scope for this item (+ create follow-up items)
  - follow-up meeting on api-test/unit-test between devs



**Example test case description:**
Given a logged-in user
And no-trigger scenario is loaded
When navigating to Uganda floods (this immediately tests switching disaster-type)
Then chat-section shows 'no events' message
And header should show Uganda floods non-triggered
And ... (add bilaterally between Piotr and 1 dev)

**Comment by gulfaraz** [comment]
### Notes from discussion with @jannisvisser and @gulfaraz 

- We picked **5 interface components** and **5 backend modules** to write unit tests.
- We agreed to write integration tests for the API endpoints of the **same 5 backend modules**.
- We agreed that prioritization is fluid so **continue this discussion during the work**.

#### Unit testing
- backend: user, typhoon-track, country, disaster, admin-area (3 public methods within each service)
- interface: map, login, user-state, disaster-type, aggregates

#### Integration testing
- works across components in the backend
- user, typhoon-track, country, disaster, admin-area (1 endpoint within each module)

Action items,
- [ ] Create follow-up issues for each track - backend unit, interface unit, integration. @gulfaraz 
- [ ] Check if the existing CI/CD setup is sufficient.

Close this issue after creating the follow up issues.
