### ISSUE TITLE
Add E2E test for "Dashboard no-trigger elements"

### ISSUE THREAD

**Issue by Piotrk39** [rodekruis/IBF-system#1592]
```[tasklist]
### Tasks
- [x] Initiate a Test Plan (for now as a document till we decide if we want to stay in Github or move to DevOps)
- [x] Add reset no-triggered function for setting the state of the IBF
- [x] Add all elements to be present in test steps
- [x] Add E2E automation script
- [x] Fix tests to run on CI
```

**Comment by Piotrk39** [comment]
Draft for the test plan:

IBF-System test plan

Uganda > Floods > no-trigger

All elements are present

Given a logged-in user
And no-trigger scenario is loaded
When navigating to Uganda floods 
Then chat-section shows 'no events' message
And header should show Uganda floods non-triggered
And

**Comment by jannisvisser** [comment]
@Piotrk39 see here a full list of elements to test on initial load of Uganda floods no-trigger.

- header
  - dev-menu/home button
  - header title (IBF Portal Uganda Floods non-triggered)
  - country logos
  - logged in as: Uganda manager
  - logout button
- top bar
  - disaster-type switch component with 3 btns for drought/floods/heavy-rain
  - current time and date
  - timeline buttons
- chat section / left column
  - speech bubble with welcome msg and 4 buttons
  - speech bubble with no alerts 
  - middle column
- aggregate section 
  - header
    - area title (National View)
    - number of events / triggered areas (0 predicted floods)
    - info icon
  - see 5 rows for 5 layers
  - per row
    - icon
    - layer name
    - number (0 in this case)
    - info icon
  - action summary
    - N/A in no-trigger
- map
  - map itself showing
    - admin-area boundary layer
    - glofas station layer
  - breadcrums (National View button only, will be more in trigger scnearios) 
  - expanded map legend
  - collapsed layer overview

**Comment by Piotrk39** [comment]
For time being test cases are stored in: https://dev.azure.com/redcrossnl/121%20Platform/_testPlans/define?planId=30494&suiteId=30495

**Comment by jannisvisser** [comment]
@gulfaraz will include in his work to have the e2e test call API endpoints instead of using API-test helper methods.
