### ISSUE TITLE
Create new test suite/cases for E2E automation

### ISSUE THREAD

**Issue by Piotrk39** [rodekruis/IBF-system#1630]
@gulfaraz discussed with @Piotrk39 for the next set of tests. We agreed on the following tasks,

```[tasklist]
### Tasks
- [x] Expand on the tests in #1619 to include interactions
- [x] Expand on the tests in #1620 to include interactions
- [x] Expand on the tests in #1621 to include interactions
- [x] Expand on the tests in #1622 to include interactions
- [x] Expand on the tests in #1596 to include interactions
- [x] Separate [timeline component tests](https://github.com/rodekruis/IBF-system/blob/50c10a0323215d7024c7442d737550fbba91d7c8/e2e/tests/DisasterType/AllDisasterTypeComponentsPresentNotrigger.spec.ts#L52) into a separate test file and consider interactions
- [x] Discuss with the devs for other IBF specific behaviour to test for. Example, GloFaS station popups in the map layer
```

@Piotrk39 If you prefer, create follow-up issues or link this issue to multiple PRs.

These tests should cover the **no-trigger** scenario to acceptable coverage. The next tests will be for the **trigger** scenario as planned in #1599.

**Comment by Piotrk39** [comment]
Based on this task I have created separate items accordingly:

1. https://github.com/orgs/rodekruis/projects/23/views/29?pane=issue&itemId=82770707&issue=rodekruis%7CIBF-system%7C1644
2. https://github.com/orgs/rodekruis/projects/23/views/29?pane=issue&itemId=82766457&issue=rodekruis%7CIBF-system%7C1638
3. https://github.com/orgs/rodekruis/projects/23/views/29?pane=issue&itemId=82766372&issue=rodekruis%7CIBF-system%7C1636
4. https://github.com/orgs/rodekruis/projects/23/views/29?pane=issue&itemId=82766527&issue=rodekruis%7CIBF-system%7C1639
5.
