### ISSUE TITLE
Add playwright reporter and separate "Timeline" component

### ISSUE THREAD

**Issue by Piotrk39** [rodekruis/IBF-system#1644]
```[tasklist]
### Tasks
- [x] Separate test for timeline present
- [x] Add playwright reporter for "Qase"
- [x] Add github app for Qase
```

**Comment by Piotrk39** [comment]
Test description: https://app.qase.io/project/IBF?case=15&suite=9
