### ISSUE TITLE
Philippines Portal bug overview

### ISSUE THREAD

**Issue by diderikvw** [rodekruis/IBF-system#1670]
Original issue of broken portal
- [x] Basic error handling that makes sure portal doesn't break if closestToLand=true point is missing (or whole track missing)
- [x] Hotfix that

Typhoon pipeline issues
- [x] The secondary data linked from the notification email is not correctly updated. > Seems fixed. Phuoc to confirm with Aki.
- [x] Pipeline is not running automatically (this is due to above bug) > Seems fixed. Phuoc to confirm with Aki.
- [x]  track was not uploaded for an event that was uploaded > Was consequence of migration bug, 
- [x] check if event 70W should not be uploaded (that's also the one with the missing track) > Was consequence of migration bug
- [x] pipeline uploaded double track also at some point > Agreed to ignore for now

Typhoon API-side
- [x] list should not show all 1647 municipalities for warning event > split off in separate [bug 889](https://github.com/rodekruis/Anticipatory-Action/issues/889)
- [x] check why event 70W has no leadTime. Should API handle this differently even though it's a pipeline issue. > This was a migration bug.
- [x] emails do not contain typhoon specific copy/scenarios any more? > added to [existing bug 880](https://github.com/rodekruis/Anticipatory-Action/issues/880)

Floods Portal
- [x] the "bug" of 0 exposed population. In email we do filter out 0 exposed pop. areas, in portal not. > split off in separate [bug 891](https://github.com/rodekruis/Anticipatory-Action/issues/891) but also related to [bug 889](https://github.com/rodekruis/Anticipatory-Action/issues/889), potentially merge.
- [x] pipeline didn't run on Wednesday > fixed
- [x] Pone's email about 3-day forecast. Explain that it was a sudden onset which we are now catching, and could not have before. > Followed up by Gal/Lars.
- [x] Discharge values inconsistencies compared to Glofas > Phuoc and Jacopo look into this
- [x] Why did threshold change after release? > Phuoc confirmed the new threshold is correct > See [separate issue 895](https://github.com/rodekruis/Anticipatory-Action/issues/895)
- [x] why did portal not trigger while discharge was over threshold (on monday before release). Not retrievable any more, we assume no longer present after release until seen again.

Longer-term
- [ ] Evaluate in general
- [ ] Dependencies on Aki for lot of specific knowledge (and similar, Jacopo)

**Comment by gulfaraz** [comment]
Potentially linked to #1552

**Comment by jannisvisser** [comment]
@p-phung so the error was with event 70W, which actually did not have a track uploaded at all (so it wasn't about closestToLand point missing, but about the whole track missing). Note that in general the track upload of the typhoon pipeline seems quite sketchy. Yesterday a seemingly double track was uploaded for 1 event (see [here](https://github.com/rodekruis/Anticipatory-Action/issues/889#issuecomment-2429468826))

Not sure, but that might also explain why the leadTimeDate is missing still now in production (this is after hotfix). 

![Image](https://github.com/user-attachments/assets/4f51185c-a880-4781-9dfe-b600d7d9bc82)

**Comment by jannisvisser** [comment]
@gulfaraz It is for sure linked to #1552 so we can either keep that and say we do the proper fix in there. Or we can do more proper fixing now and delete that one. I guess the first option right?

**Comment by gulfaraz** [comment]
Let's limit the scope of this issue to the hotfix. And move #1552 to the top of the backlog.

**Comment by gulfaraz** [comment]
@jannisvisser identified this when testing the refactored pipeline. @jmargutt explained this as [expected behaviour](https://teams.microsoft.com/l/message/19:b262590b1cc34ade9bbdb584f0765b31@thread.skype/1727701200344?tenantId=d3ab9790-6ae2-4bd8-aa5e-02864483e7c7&groupId=48e3c654-ac7d-4abc-9c70-ad637fb0a85f&parentMessageId=1727689456065&teamName=510%20-%20Anticipatory%20Action&channelName=IBF%20-%20System&createdTime=1727701200344).

@jannisvisser and I discussed this after the release, he noted a discrepancy in the list of areas shown in the dashboard vs the email.

From what I gather,
1. The pipeline can mark an admin area as exposed but still have a primary indicator value of 0. [Source](https://teams.microsoft.com/l/message/19:b262590b1cc34ade9bbdb584f0765b31@thread.skype/1727701200344?tenantId=d3ab9790-6ae2-4bd8-aa5e-02864483e7c7&groupId=48e3c654-ac7d-4abc-9c70-ad637fb0a85f&parentMessageId=1727689456065&teamName=510%20-%20Anticipatory%20Action&channelName=IBF%20-%20System&createdTime=1727701200344)
2. The dashboard shows the list of admin areas regardless of the primary indicator value. The dashboard's purpose is to show the values sent by the pipeline.
3. The email filters out the admin areas with a primary indicator value of 0. This was requested by design [here](https://github.com/rodekruis/Anticipatory-Action/issues/646). This change introduced the discrepancy between the dashboard and the email.

> please let me know if I should open a different bug or there is already a ticket for it

We have [an open bug](https://github.com/rodekruis/Anticipatory-Action/issues/891) for this issue. @jannisvisser has provided [a similar explanation there](https://github.com/rodekruis/Anticipatory-Action/issues/891#issuecomment-2431180840).

**Comment by gal-agmon** [comment]
> [@jannisvisser](https://github.com/jannisvisser) identified this when testing the refactored pipeline. [@jmargutt](https://github.com/jmargutt) explained this as [expected behaviour](https://teams.microsoft.com/l/message/19:b262590b1cc34ade9bbdb584f0765b31@thread.skype/1727701200344?tenantId=d3ab9790-6ae2-4bd8-aa5e-02864483e7c7&groupId=48e3c654-ac7d-4abc-9c70-ad637fb0a85f&parentMessageId=1727689456065&teamName=510%20-%20Anticipatory%20Action&channelName=IBF%20-%20System&createdTime=1727701200344).
> 
> [@jannisvisser](https://github.com/jannisvisser) and I discussed this after the release, he noted a discrepancy in the list of areas shown in the dashboard vs the email.
> 
> From what I gather,
> 
> 1. The pipeline can mark an admin area as exposed but still have a primary indicator value of 0. [Source](https://teams.microsoft.com/l/message/19:b262590b1cc34ade9bbdb584f0765b31@thread.skype/1727701200344?tenantId=d3ab9790-6ae2-4bd8-aa5e-02864483e7c7&groupId=48e3c654-ac7d-4abc-9c70-ad637fb0a85f&parentMessageId=1727689456065&teamName=510%20-%20Anticipatory%20Action&channelName=IBF%20-%20System&createdTime=1727701200344)
> 2. The dashboard shows the list of admin areas regardless of the primary indicator value. The dashboard's purpose is to show the values sent by the pipeline.
> 3. The email filters out the admin areas with a primary indicator value of 0. This was requested by design [here](https://github.com/rodekruis/Anticipatory-Action/issues/646). This change introduced the discrepancy between the dashboard and the email.
> 
> > please let me know if I should open a different bug or there is already a ticket for it
> 
> We have [an open bug](https://github.com/rodekruis/Anticipatory-Action/issues/891) for this issue. [@jannisvisser](https://github.com/jannisvisser) has provided [a similar explanation there](https://github.com/rodekruis/Anticipatory-Action/issues/891#issuecomment-2431180840).
 Yes I opened that bug :) makes sense it is the same will add the screen shot there. Thanks!

**Comment by jannisvisser** [comment]
@diderikvw FYI Just one open point in above checklist, which is to be updated by @p-phung.

**Comment by jannisvisser** [comment]
Good to be aware of for @BlaiseSelvan when she's back, so leaving in 'to accept'

**Comment by BlaiseSelvan** [comment]
Hi @jannisvisser thanks for tagging me and 'leaving it in accept'. Looks like a lot of bugs etc. l need more context to understand this properly. Catching up with Diderik tomorrow. Do you think it would be good for us to catch up on this too?

**Comment by jannisvisser** [comment]
@BlaiseSelvan that depends on your talk with @diderikvw. Please call me in if relevant and/or determine afterwards if it's still relevant to talk to me.

**Comment by BlaiseSelvan** [comment]
Okay will do @jannisvisser.
